[build]
target = "thumbv8m.main-none-eabi"
rustflags = [
  "-C", "link-arg=-Tlinker.ld",
  "-C", "target-feature=+cmse"
]

[target.thumbv8m.main-none-eabi]
rustflags = [
  "-C", "link-arg=-Tlink.x"       # これだけで十分
]

# hv/Cargo.toml
[package.metadata.cortex-m-rt]
# デフォルト memory.x を無効化
omit-gcc-check = true
memory.x = "memory.x"

[env]
# panic* クレートのログを uart0 に流したい場合などはここに追記

[alias]
hv   = "build -p hv     --release"
vm0   = "build -p vm0  --release"

[workspace]
resolver = "2"
